# CMake generated Testfile for 
# Source directory: /home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so
# Build directory: /home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit.gpup.nonameaction "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest/unit.gpup.nonameaction")
set_tests_properties(unit.gpup.nonameaction PROPERTIES  WORKING_DIRECTORY "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest" _BACKTRACE_TRIPLES "/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;59;add_test;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests.cmake;31;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/CMakeLists.txt;146;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/CMakeLists.txt;0;")
add_test(ttp.conf.log.gpup.single "/home/samwu103/Documents/GitHub/ROCmValidationSuite/regression/run_and_check_test.py" "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bin" "/home/samwu103/Documents/GitHub/ROCmValidationSuite" "conf/gpup_single.conf" "true" "true" "true" "ttp" "3")
set_tests_properties(ttp.conf.log.gpup.single PROPERTIES  WORKING_DIRECTORY "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bin" _BACKTRACE_TRIPLES "/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests_conf_ttp.cmake;26;add_test;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests_conf_ttp.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_conf_logging.cmake;49;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_conf_logging.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests.cmake;33;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/tests.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/CMakeLists.txt;146;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/gpup.so/CMakeLists.txt;0;")
