#date
#echo 'rcqt_2';sudo ./rvs -c conf/rcqt_2.conf -d 3; date
#echo 'rcqt_3';sudo ./rvs -c conf/rcqt_3.conf -d 3; date
#echo 'rcqt_4';sudo ./rvs -c conf/rcqt_4.conf -d 3; date
#echo 'rcqt_fc_1';sudo ./rvs -c conf/rcqt_fc_1.conf -d 3; date
#echo 'rcqt_fc_2';sudo ./rvs -c conf/rcqt_fc_2.conf -d 3; date
#echo 'rcqt_fc_3';sudo ./rvs -c conf/rcqt_fc_3.conf -d 3; date
#echo 'rcqt_fc_4';sudo ./rvs -c conf/rcqt_fc_4.conf -d 3; date
#echo 'rcqt_fc_5';sudo ./rvs -c conf/rcqt_fc_5.conf -d 3; date
#echo 'rcqt_fc_centos1';sudo ./rvs -c conf/rcqt_fc_centos1.conf -d 3; date
#echo 'rcqt_filechk_centos';sudo ./rvs -c conf/rcqt_filechk_centos.conf -d 3; date
#echo 'rcqt_kernel_fail_1';sudo ./rvs -c conf/rcqt_kernel_fail_1.conf -d 3; date
#echo 'rcqt_kernel_fail_2';sudo ./rvs -c conf/rcqt_kernel_fail_2.conf -d 3; date
#echo 'rcqt_kernel_pass_1';sudo ./rvs -c conf/rcqt_kernel_pass_1.conf -d 3; date
#echo 'rcqt_kernel_pass_2';sudo ./rvs -c conf/rcqt_kernel_pass_2.conf -d 3; date
#echo 'rcqt_kernel_pass_3';sudo ./rvs -c conf/rcqt_kernel_pass_3.conf -d 3; date
#echo 'rcqt_kernel_pass_centos1';sudo ./rvs -c conf/rcqt_kernel_pass_centos1.conf -d 3; date
#echo 'rcqt_ldchk_cent1';sudo ./rvs -c conf/rcqt_ldchk_cent1.conf -d 3; date
#echo 'rcqt_ldchk_centos';sudo ./rvs -c conf/rcqt_ldchk_centos.conf -d 3; date
#echo 'rcqt_ldchk_fail1';sudo ./rvs -c conf/rcqt_ldchk_fail1.conf -d 3; date
#echo 'rcqt_ldchk_fail2';sudo ./rvs -c conf/rcqt_ldchk_fail2.conf -d 3; date
#echo 'rcqt_ldchk_fail3';sudo ./rvs -c conf/rcqt_ldchk_fail3.conf -d 3; date
#echo 'rcqt_ldchk_pass';sudo ./rvs -c conf/rcqt_ldchk_pass.conf -d 3; date
#echo 'rcqt_ldchk_pass1';sudo ./rvs -c conf/rcqt_ldchk_pass1.conf -d 3; date
#echo 'rcqt_ldchk_pass2';sudo ./rvs -c conf/rcqt_ldchk_pass2.conf -d 3; date
#echo 'rcqt_pkg_fail1';sudo ./rvs -c conf/rcqt_pkg_fail1.conf -d 3; date
#echo 'rcqt_pkg_fail2';sudo ./rvs -c conf/rcqt_pkg_fail2.conf -d 3; date
#echo 'rcqt_pkg_pass';sudo ./rvs -c conf/rcqt_pkg_pass.conf -d 3; date
#echo 'rcqt_pkg_pass2';sudo ./rvs -c conf/rcqt_pkg_pass2.conf -d 3; date
#echo 'rcqt_pkg_pass3';sudo ./rvs -c conf/rcqt_pkg_pass3.conf -d 3; date
#echo 'rcqt_pkg_pass4';sudo ./rvs -c conf/rcqt_pkg_pass4.conf -d 3; date
#echo 'rcqt_usr_pass1';sudo ./rvs -c conf/rcqt_usr_pass1.conf -d 3; date
#echo 'rcqt_usr_pass2';sudo ./rvs -c conf/rcqt_usr_pass2.conf -d 3; date
#echo 'rcqt_usr_pass3';sudo ./rvs -c conf/rcqt_usr_pass3.conf -d 3; date
#echo 'rcqt_usr_pass4';sudo ./rvs -c conf/rcqt_usr_pass4.conf -d 3; date
#echo 'rcqt_usr_pass5';sudo ./rvs -c conf/rcqt_usr_pass5.conf -d 3; date
