date
echo 'ttf_gm_11';sudo ./rvs -c conf/ttf_gm_11.conf -d 3;date
echo 'ttf_gm_12';sudo ./rvs -c conf/ttf_gm_12.conf -d 3;date
echo 'ttf_gm_21';sudo ./rvs -c conf/ttf_gm_21.conf -d 3;date
echo 'ttf_gm_22';sudo ./rvs -c conf/ttf_gm_22.conf -d 3;date
echo 'ttf_gm_31';sudo ./rvs -c conf/ttf_gm_31.conf -d 3;date
echo 'ttf_gm_32';sudo ./rvs -c conf/ttf_gm_32.conf -d 3;date
echo 'ttf_gm_41';sudo ./rvs -c conf/ttf_gm_41.conf -d 3;date
echo 'ttf_gm_42';sudo ./rvs -c conf/ttf_gm_42.conf -d 3;date
echo 'ttf_gm_4';sudo ./rvs -c conf/ttf_gm_4.conf -d 3;date
echo 'ttf_gm_51';sudo ./rvs -c conf/ttf_gm_51.conf -d 3;date
echo 'ttf_gm_52';sudo ./rvs -c conf/ttf_gm_52.conf -d 3;date
echo 'ttf_gm_6';sudo ./rvs -c conf/ttf_gm_6.conf -d 3;date
echo 'ttf_gm_8';sudo ./rvs -c conf/ttf_gm_8.conf -d 3;date
echo 'ttf_gm_9';sudo ./rvs -c conf/ttf_gm_9.conf -d 3;date
echo 'ttf_gm_invalid_common_keys';sudo ./rvs -c conf/ttf_gm_invalid_common_keys.conf -d 3;date
echo 'ttf_gm_invalid_gm_keys';sudo ./rvs -c conf/ttf_gm_invalid_gm_keys.conf -d 3;date
echo 'ttf_gm_no_action_name';sudo ./rvs -c conf/ttf_gm_no_action_name.conf -d 3;date
echo 'ttf_gm_no_device';sudo ./rvs -c conf/ttf_gm_no_device.conf -d 3;date
echo 'ttf_gpup_1';sudo ./rvs -c conf/ttf_gpup_1.conf -d 3;date
echo 'ttf_gpup_2';sudo ./rvs -c conf/ttf_gpup_2.conf -d 3;date
echo 'ttf_gpup_3';sudo ./rvs -c conf/ttf_gpup_3.conf -d 3;date
echo 'ttf_gpup_8';sudo ./rvs -c conf/ttf_gpup_8.conf -d 3;date
echo 'ttf_gpup_9';sudo ./rvs -c conf/ttf_gpup_9.conf -d 3;date
echo 'ttf_gst_invalid_common_keys';sudo ./rvs -c conf/ttf_gst_invalid_common_keys.conf -d 3;date
echo 'ttf_gst_invalid_gst_keys';sudo ./rvs -c conf/ttf_gst_invalid_gst_keys.conf -d 3;date
echo 'ttf_gst_no_action_name';sudo ./rvs -c conf/ttf_gst_no_action_name.conf -d 3;date
echo 'ttf_gst_no_device_key';sudo ./rvs -c conf/ttf_gst_no_device_key.conf -d 3;date
echo 'ttf_gst_no_devices';sudo ./rvs -c conf/ttf_gst_no_devices.conf -d 3;date
echo 'ttf_gst_no_target_stress';sudo ./rvs -c conf/ttf_gst_no_target_stress.conf -d 3;date
echo 'ttf_gst_ramp_too_long';sudo ./rvs -c conf/ttf_gst_ramp_too_long.conf -d 3;date
echo 'ttf_iet_6';sudo ./rvs -c conf/ttf_iet_6.conf -d 3;date
echo 'ttf_iet_invalid_common_keys';sudo ./rvs -c conf/ttf_iet_invalid_common_keys.conf -d 3;date
echo 'ttf_iet_invalid_iet_keys';sudo ./rvs -c conf/ttf_iet_invalid_iet_keys.conf -d 3;date
echo 'ttf_iet_no_actione_name';sudo ./rvs -c conf/ttf_iet_no_action_name.conf -d 3;date
echo 'ttf_iet_no_device_key';sudo ./rvs -c conf/ttf_iet_no_device_key.conf -d 3;date
echo 'ttf_iet_no_target_power';sudo ./rvs -c conf/ttf_iet_no_target_power.conf -d 3;date
echo 'ttf_iet_ramp_too_long';sudo ./rvs -c conf/ttf_iet_ramp_too_long.conf -d 3;date
echo 'ttf_pebb_device_criteri_fail';sudo ./rvs -c conf/ttf_pebb_device_criteri_fail.conf -d 3;date
echo 'ttf_pebb_invalid_common_keys';sudo ./rvs -c conf/ttf_pebb_invalid_common_keys.conf -d 3;date
echo 'ttf_pebb_invalid_pebb_keys';sudo ./rvs -c conf/ttf_pebb_invalid_pebb_keys.conf -d 3;date
echo 'ttf_pebb_no_action_name';sudo ./rvs -c conf/ttf_pebb_no_action_name.conf -d 3;date
echo 'ttf_pebb_no_device';sudo ./rvs -c conf/ttf_pebb_no_device.conf -d 3;date
echo 'ttf_peqt_deviceid_notfound';sudo ./rvs -c conf/ttf_peqt_deviceid_notfound.conf -d 3;date
echo 'ttf_peqt_invalid_common_keys';sudo ./rvs -c conf/ttf_peqt_invalid_common_keys.conf -d 3;date
echo 'ttf_peqt_no_action_name';sudo ./rvs -c conf/ttf_peqt_no_action_name.conf -d 3;date
echo 'ttf_peqt_no_device';sudo ./rvs -c conf/ttf_peqt_no_device.conf -d 3;date
echo 'ttf_pesm_3';sudo ./rvs -c conf/ttf_pesm_3.conf -d 3;date
echo 'ttf_pesm_4';sudo ./rvs -c conf/ttf_pesm_4.conf -d 3;date
echo 'ttf_pesm_6';sudo ./rvs -c conf/ttf_pesm_6.conf -d 3;date
echo 'ttf_pesm_7';sudo ./rvs -c conf/ttf_pesm_7.conf -d 3;date
echo 'ttf_pqt_10';sudo ./rvs -c conf/ttf_pqt_10.conf -d 3;date
echo 'ttf_pqt_1';sudo ./rvs -c conf/ttf_pqt_1.conf -d 3;date
echo 'ttf_pqt_2';sudo ./rvs -c conf/ttf_pqt_2.conf -d 3;date
echo 'ttf_pqt_3';sudo ./rvs -c conf/ttf_pqt_3.conf -d 3;date
echo 'ttf_pqt_4';sudo ./rvs -c conf/ttf_pqt_4.conf -d 3;date
echo 'ttf_pqt_5';sudo ./rvs -c conf/ttf_pqt_5.conf -d 3;date
echo 'ttf_pqt_6';sudo ./rvs -c conf/ttf_pqt_6.conf -d 3;date
echo 'ttf_pqt_7';sudo ./rvs -c conf/ttf_pqt_7.conf -d 3;date
echo 'ttf_pqt_8';sudo ./rvs -c conf/ttf_pqt_8.conf -d 3;date
echo 'ttf_pqt_9';sudo ./rvs -c conf/ttf_pqt_9.conf -d 3;date
echo 'ttf_rcqt_kernel_fail';sudo ./rvs -c conf/ttf_rcqt_kernel_fail.conf -d 3;date
echo 'ttf_rcqt_ldchk_no_arch';sudo ./rvs -c conf/ttf_rcqt_ldchk_no_arch.conf -d 3;date
echo 'ttf_rcqt_ldchk_no_path';sudo ./rvs -c conf/ttf_rcqt_ldchk_no_path.conf -d 3;date
echo 'ttf_smqt_1';sudo ./rvs -c conf/ttf_smqt_1.conf -d 3;date
echo 'ttf_smqt_actionname';sudo ./rvs -c conf/ttf_smqt_actionname.conf -d 3;date
echo 'ttf_smqt_bar1addrmissing';sudo ./rvs -c conf/ttf_smqt_bar1addrmissing.conf -d 3;date
echo 'ttf_smqt_baraddrfalse';sudo ./rvs -c conf/ttf_smqt_baraddrfalse.conf -d 3;date
echo 'ttf_smqt_deviceinvalid';sudo ./rvs -c conf/ttf_smqt_deviceidinvalid.conf -d 3;date
echo 'ttf_smqt_deviceid_invalidnum';sudo ./rvs -c conf/ttf_smqt_deviceid_invalidnum.conf -d 3;date
echo 'ttf_smqt_deviceinvalid';sudo ./rvs -c conf/ttf_smqt_deviceinvalid.conf -d 3;date
echo 'ttf_smqt_devicemissing';sudo ./rvs -c conf/ttf_smqt_devicemissing.conf -d 3;date
echo 'ttf_testif_fail_create_action';sudo ./rvs -c conf/ttf_testif_fail_create_action.conf -d 3;date
echo 'ttf_testif_fail_init';sudo ./rvs -c conf/ttf_testif_fail_init.conf -d 3;date
echo 'ttf_testif_if0_no';sudo ./rvs -c conf/ttf_testif_if0_no.conf -d 3;date
echo 'ttf_testif_if0_no_methods';sudo ./rvs -c conf/ttf_testif_if0_no_methods.conf -d 3;date
echo 'ttf_testif_if1_no';sudo ./rvs -c conf/ttf_testif_if1_no.conf -d 3;date
echo 'ttf_testif_if1_no_methods';sudo ./rvs -c conf/ttf_testif_if1_no_methods.conf -d 3;date
echo 'ttf_testif_if_no_methods';sudo ./rvs -c conf/ttf_testif_if_no_methods.conf -d 3;date

