#!/bin/sh
date
echo 'ttf_gm_11';sudo ../../../bin/rvs -c ../conf/ttf_gm_11.conf -d 3;date
echo 'ttf_gm_12';sudo ../../../bin/rvs -c ../conf/ttf_gm_12.conf -d 3;date
echo 'ttf_gm_21';sudo ../../../bin/rvs -c ../conf/ttf_gm_21.conf -d 3;date
echo 'ttf_gm_22';sudo ../../../bin/rvs -c ../conf/ttf_gm_22.conf -d 3;date
echo 'ttf_gm_31';sudo ../../../bin/rvs -c ../conf/ttf_gm_31.conf -d 3;date
echo 'ttf_gm_32';sudo ../../../bin/rvs -c ../conf/ttf_gm_32.conf -d 3;date
echo 'ttf_gm_41';sudo ../../../bin/rvs -c ../conf/ttf_gm_41.conf -d 3;date
echo 'ttf_gm_42';sudo ../../../bin/rvs -c ../conf/ttf_gm_42.conf -d 3;date
echo 'ttf_gm_4';sudo ../../../bin/rvs -c ../conf/ttf_gm_4.conf -d 3;date
echo 'ttf_gm_51';sudo ../../../bin/rvs -c ../conf/ttf_gm_51.conf -d 3;date
echo 'ttf_gm_52';sudo ../../../bin/rvs -c ../conf/ttf_gm_52.conf -d 3;date
echo 'ttf_gm_6';sudo ../../../bin/rvs -c ../conf/ttf_gm_6.conf -d 3;date
echo 'ttf_gm_8';sudo ../../../bin/rvs -c ../conf/ttf_gm_8.conf -d 3;date
echo 'ttf_gm_9';sudo ../../../bin/rvs -c ../conf/ttf_gm_9.conf -d 3;date
echo 'ttf_gm_invalid_common_keys';sudo ../../../bin/rvs -c ../conf/ttf_gm_invalid_common_keys.conf -d 3;date
echo 'ttf_gm_invalid_gm_keys';sudo ../../../bin/rvs -c ../conf/ttf_gm_invalid_gm_keys.conf -d 3;date
echo 'ttf_gm_no_action_name';sudo ../../../bin/rvs -c ../conf/ttf_gm_no_action_name.conf -d 3;date
echo 'ttf_gm_no_device';sudo ../../../bin/rvs -c ../conf/ttf_gm_no_device.conf -d 3;date
echo 'ttf_gpup_1';sudo ../../../bin/rvs -c ../conf/ttf_gpup_1.conf -d 3;date
echo 'ttf_gpup_2';sudo ../../../bin/rvs -c ../conf/ttf_gpup_2.conf -d 3;date
echo 'ttf_gpup_3';sudo ../../../bin/rvs -c ../conf/ttf_gpup_3.conf -d 3;date
echo 'ttf_gpup_8';sudo ../../../bin/rvs -c ../conf/ttf_gpup_8.conf -d 3;date
echo 'ttf_gpup_9';sudo ../../../bin/rvs -c ../conf/ttf_gpup_9.conf -d 3;date
echo 'ttf_gst_invalid_common_keys';sudo ../../../bin/rvs -c ../conf/ttf_gst_invalid_common_keys.conf -d 3;date
echo 'ttf_gst_invalid_gst_keys';sudo ../../../bin/rvs -c ../conf/ttf_gst_invalid_gst_keys.conf -d 3;date
echo 'ttf_gst_no_action_name';sudo ../../../bin/rvs -c ../conf/ttf_gst_no_action_name.conf -d 3;date
echo 'ttf_gst_no_device_key';sudo ../../../bin/rvs -c ../conf/ttf_gst_no_device_key.conf -d 3;date
echo 'ttf_gst_no_devices';sudo ../../../bin/rvs -c ../conf/ttf_gst_no_devices.conf -d 3;date
echo 'ttf_gst_no_target_stress';sudo ../../../bin/rvs -c ../conf/ttf_gst_no_target_stress.conf -d 3;date
echo 'ttf_gst_ramp_too_long';sudo ../../../bin/rvs -c ../conf/ttf_gst_ramp_too_long.conf -d 3;date
echo 'ttf_iet_6';sudo ../../../bin/rvs -c ../conf/ttf_iet_6.conf -d 3;date
echo 'ttf_iet_invalid_common_keys';sudo ../../../bin/rvs -c ../conf/ttf_iet_invalid_common_keys.conf -d 3;date
echo 'ttf_iet_invalid_iet_keys';sudo ../../../bin/rvs -c ../conf/ttf_iet_invalid_iet_keys.conf -d 3;date
echo 'ttf_iet_no_actione_name';sudo ../../../bin/rvs -c ../conf/ttf_iet_no_action_name.conf -d 3;date
echo 'ttf_iet_no_device_key';sudo ../../../bin/rvs -c ../conf/ttf_iet_no_device_key.conf -d 3;date
echo 'ttf_iet_no_target_power';sudo ../../../bin/rvs -c ../conf/ttf_iet_no_target_power.conf -d 3;date
echo 'ttf_iet_ramp_too_long';sudo ../../../bin/rvs -c ../conf/ttf_iet_ramp_too_long.conf -d 3;date
echo 'ttf_pebb_device_criteri_fail';sudo ../../../bin/rvs -c ../conf/ttf_pebb_device_criteri_fail.conf -d 3;date
echo 'ttf_pebb_invalid_common_keys';sudo ../../../bin/rvs -c ../conf/ttf_pebb_invalid_common_keys.conf -d 3;date
echo 'ttf_pebb_invalid_pebb_keys';sudo ../../../bin/rvs -c ../conf/ttf_pebb_invalid_pebb_keys.conf -d 3;date
echo 'ttf_pebb_no_action_name';sudo ../../../bin/rvs -c ../conf/ttf_pebb_no_action_name.conf -d 3;date
echo 'ttf_pebb_no_device';sudo ../../../bin/rvs -c ../conf/ttf_pebb_no_device.conf -d 3;date
echo 'ttf_peqt_deviceid_notfound';sudo ../../../bin/rvs -c ../conf/ttf_peqt_deviceid_notfound.conf -d 3;date
echo 'ttf_peqt_invalid_common_keys';sudo ../../../bin/rvs -c ../conf/ttf_peqt_invalid_common_keys.conf -d 3;date
echo 'ttf_peqt_no_action_name';sudo ../../../bin/rvs -c ../conf/ttf_peqt_no_action_name.conf -d 3;date
echo 'ttf_peqt_no_device';sudo ../../../bin/rvs -c ../conf/ttf_peqt_no_device.conf -d 3;date
echo 'ttf_pesm_3';sudo ../../../bin/rvs -c ../conf/ttf_pesm_3.conf -d 3;date
echo 'ttf_pesm_4';sudo ../../../bin/rvs -c ../conf/ttf_pesm_4.conf -d 3;date
echo 'ttf_pesm_6';sudo ../../../bin/rvs -c ../conf/ttf_pesm_6.conf -d 3;date
echo 'ttf_pesm_7';sudo ../../../bin/rvs -c ../conf/ttf_pesm_7.conf -d 3;date
echo 'ttf_pbqt_10';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_10.conf -d 3;date
echo 'ttf_pbqt_1';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_1.conf -d 3;date
echo 'ttf_pbqt_2';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_2.conf -d 3;date
echo 'ttf_pbqt_3';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_3.conf -d 3;date
echo 'ttf_pbqt_4';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_4.conf -d 3;date
echo 'ttf_pbqt_5';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_5.conf -d 3;date
echo 'ttf_pbqt_6';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_6.conf -d 3;date
echo 'ttf_pbqt_7';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_7.conf -d 3;date
echo 'ttf_pbqt_8';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_8.conf -d 3;date
echo 'ttf_pbqt_9';sudo ../../../bin/rvs -c ../conf/ttf_pbqt_9.conf -d 3;date
echo 'ttf_rcqt_kernel_fail';sudo ../../../bin/rvs -c ../conf/ttf_rcqt_kernel_fail.conf -d 3;date
echo 'ttf_rcqt_ldchk_no_arch';sudo ../../../bin/rvs -c ../conf/ttf_rcqt_ldchk_no_arch.conf -d 3;date
echo 'ttf_rcqt_ldchk_no_path';sudo ../../../bin/rvs -c ../conf/ttf_rcqt_ldchk_no_path.conf -d 3;date
echo 'ttf_smqt_1';sudo ../../../bin/rvs -c ../conf/ttf_smqt_1.conf -d 3;date
echo 'ttf_smqt_actionname';sudo ../../../bin/rvs -c ../conf/ttf_smqt_actionname.conf -d 3;date
echo 'ttf_smqt_bar1addrmissing';sudo ../../../bin/rvs -c ../conf/ttf_smqt_bar1addrmissing.conf -d 3;date
echo 'ttf_smqt_baraddrfalse';sudo ../../../bin/rvs -c ../conf/ttf_smqt_baraddrfalse.conf -d 3;date
echo 'ttf_smqt_deviceinvalid';sudo ../../../bin/rvs -c ../conf/ttf_smqt_deviceidinvalid.conf -d 3;date
echo 'ttf_smqt_deviceid_invalidnum';sudo ../../../bin/rvs -c ../conf/ttf_smqt_deviceid_invalidnum.conf -d 3;date
echo 'ttf_smqt_deviceinvalid';sudo ../../../bin/rvs -c ../conf/ttf_smqt_deviceinvalid.conf -d 3;date
echo 'ttf_smqt_devicemissing';sudo ../../../bin/rvs -c ../conf/ttf_smqt_devicemissing.conf -d 3;date
echo 'ttf_testif_fail_create_action';sudo ../../../bin/rvs -c ../conf/ttf_testif_fail_create_action.conf -d 3;date
echo 'ttf_testif_fail_init';sudo ../../../bin/rvs -c ../conf/ttf_testif_fail_init.conf -d 3;date
echo 'ttf_testif_if0_no';sudo ../../../bin/rvs -c ../conf/ttf_testif_if0_no.conf -d 3;date
echo 'ttf_testif_if0_no_methods';sudo ../../../bin/rvs -c ../conf/ttf_testif_if0_no_methods.conf -d 3;date
echo 'ttf_testif_if1_no';sudo ../../../bin/rvs -c ../conf/ttf_testif_if1_no.conf -d 3;date
echo 'ttf_testif_if1_no_methods';sudo ../../../bin/rvs -c ../conf/ttf_testif_if1_no_methods.conf -d 3;date
echo 'ttf_testif_if_no_methods';sudo ../../../bin/rvs -c ../conf/ttf_testif_if_no_methods.conf -d 3;date

