#!/bin/bash

# arguments:
#   bin path
#   conf file
#   json output
#   console output

cd $1

if [ -f $4 ]
then
   rm $4
fi

if [ "$3" = "no_json" ]
then
   ./rvs -c $2 > $4
else
   if [ -f $3 ]
   then
      rm $3
   fi
   ./rvs -c $2 -l $3 -j > $4
fi
