echo 'mix_gmgst1';sudo ./rvs -c conf/mix_gmgst1.conf -d 3;  date
echo 'mix_gmgst2';sudo ./rvs -c conf/mix_gmgst2.conf -d 3; date
echo 'mix_gmgst3';sudo ./rvs -c conf/mix_gmgst3.conf -d 3; date
echo 'mix_gmiet';sudo ./rvs -c conf/mix_gmiet.conf -d 3; date
echo 'mix_gmiet1';sudo ./rvs -c conf/mix_gmiet1.conf -d 3; date
echo 'mix_gmpebb1';sudo ./rvs -c conf/mix_gmpebb1.conf -d 3; date
echo 'mix_gmpebb2';sudo ./rvs -c conf/mix_gmpebb2.conf -d 3; date
echo 'mix_gmpebb3';sudo ./rvs -c conf/mix_gmpebb3.conf -d 3; date
echo 'mix_gmpebb4';sudo ./rvs -c conf/mix_gmpebb4.conf -d 3; date
