.TH "md_doc_mansrc_rvs" 1 "Thu Oct 18 2018" "Version 0.0.22" "RVS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_doc_mansrc_rvs \- rvs 
/********************************************************************************
.IP "\(bu" 2

.IP "\(bu" 2
Copyright (c) 2018 ROCm Developer Tools
.IP "\(bu" 2

.IP "\(bu" 2
MIT LICENSE:
.IP "\(bu" 2
Permission is hereby granted, free of charge, to any person obtaining a copy of
.IP "\(bu" 2
this software and associated documentation files (the 'Software'), to deal in
.IP "\(bu" 2
the Software without restriction, including without limitation the rights to
.IP "\(bu" 2
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
.IP "\(bu" 2
of the Software, and to permit persons to whom the Software is furnished to do
.IP "\(bu" 2
so, subject to the following conditions:
.IP "\(bu" 2

.IP "\(bu" 2
The above copyright notice and this permission notice shall be included in all
.IP "\(bu" 2
copies or substantial portions of the Software\&.
.IP "\(bu" 2

.IP "\(bu" 2
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.IP "\(bu" 2
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.IP "\(bu" 2
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE
.IP "\(bu" 2
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.IP "\(bu" 2
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.IP "\(bu" 2
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
.IP "\(bu" 2
SOFTWARE\&.
.IP "\(bu" 2
*******************************************************************************/ 
.PP

