# CMake generated Testfile for 
# Source directory: /home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so
# Build directory: /home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit.pesm.actionbase "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest/unit.pesm.actionbase")
set_tests_properties(unit.pesm.actionbase PROPERTIES  WORKING_DIRECTORY "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest" _BACKTRACE_TRIPLES "/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;59;add_test;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;31;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;143;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;0;")
add_test(unit.pesm.sanity "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest/unit.pesm.sanity")
set_tests_properties(unit.pesm.sanity PROPERTIES  WORKING_DIRECTORY "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bintest" _BACKTRACE_TRIPLES "/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;59;add_test;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_unit.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;31;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;143;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;0;")
add_test(ttp.conf.log.pesm.1 "/home/samwu103/Documents/GitHub/ROCmValidationSuite/regression/run_and_check_test.py" "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bin" "/home/samwu103/Documents/GitHub/ROCmValidationSuite" "conf/pesm_1.conf" "true" "true" "true" "ttp" "3")
set_tests_properties(ttp.conf.log.pesm.1 PROPERTIES  WORKING_DIRECTORY "/home/samwu103/Documents/GitHub/ROCmValidationSuite/bin" _BACKTRACE_TRIPLES "/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests_conf_ttp.cmake;26;add_test;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests_conf_ttp.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_conf_logging.cmake;49;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/cmake_modules/tests_conf_logging.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;34;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/tests.cmake;0;;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;143;include;/home/samwu103/Documents/GitHub/ROCmValidationSuite/pesm.so/CMakeLists.txt;0;")
